/**
 * Below are the colors that are used in the app. The colors are defined in the light and dark mode.
 * There are many other ways to style your app. For example, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.
 */

const tintColorLight = "#0a7ea4";
const tintColorDark = "#fff";

const nutrisyncColors = {
  light: {
    primary: "#405F90",
    surfaceTint: "#405F90",
    onPrimary: "#FFFFFF",
    primaryContainer: "#D6E3FF",
    onPrimaryContainer: "#001B3D",
    secondary: "#555F71",
    onSecondary: "#FFFFFF",
    secondaryContainer: "#D9E3F9",
    onSecondaryContainer: "#121C2B",
    tertiary: "#6F5675",
    onTertiary: "#FFFFFF",
    tertiaryContainer: "#F9D8FD",
    onTertiaryContainer: "#28132F",
    error: "#BA1A1A",
    onError: "#FFFFFF",
    errorContainer: "#FFDAD6",
    onErrorContainer: "#410002",
    background: "#F9F9FF",
    onBackground: "#191C20",
    surface: "#F9F9FF",
    onSurface: "#191C20",
    surfaceVariant: "#E0E2EC",
    onSurfaceVariant: "#44474E",
    outline: "#74777F",
    outlineVariant: "#C4C6CF",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: "#2E3036",
    inverseOnSurface: "#F0F0F7",
    inversePrimary: "#A9C7FF",
    primaryFixed: "#D6E3FF",
    onPrimaryFixed: "#001B3D",
    primaryFixedDim: "#A9C7FF",
    onPrimaryFixedVariant: "#264777",
    secondaryFixed: "#D9E3F9",
    onSecondaryFixed: "#121C2B",
    secondaryFixedDim: "#BDC7DC",
    onSecondaryFixedVariant: "#3E4758",
    tertiaryFixed: "#F9D8FD",
    onTertiaryFixed: "#28132F",
    tertiaryFixedDim: "#DCBCE1",
    onTertiaryFixedVariant: "#563E5C",
    surfaceDim: "#D9D9E0",
    surfaceBright: "#F9F9FF",
    surfaceContainerLowest: "#FFFFFF",
    surfaceContainerLow: "#F3F3FA",
    surfaceContainer: "#EDEDF4",
    surfaceContainerHigh: "#E7E8EE",
    surfaceContainerHighest: "#E2E2E9",
  },
  dark: {
    primary: "#A9C7FF",
    surfaceTint: "#A9C7FF",
    onPrimary: "#08305F",
    primaryContainer: "#264777",
    onPrimaryContainer: "#D6E3FF",
    secondary: "#BDC7DC",
    onSecondary: "#273141",
    secondaryContainer: "#3E4758",
    onSecondaryContainer: "#D9E3F9",
    tertiary: "#DCBCE1",
    onTertiary: "#3E2845",
    tertiaryContainer: "#563E5C",
    onTertiaryContainer: "#F9D8FD",
    error: "#FFB4AB",
    onError: "#690005",
    errorContainer: "#93000A",
    onErrorContainer: "#FFDAD6",
    background: "#111318",
    onBackground: "#E2E2E9",
    surface: "#111318",
    onSurface: "#E2E2E9",
    surfaceVariant: "#44474E",
    onSurfaceVariant: "#C4C6CF",
    outline: "#8E9099",
    outlineVariant: "#44474E",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: "#E2E2E9",
    inverseOnSurface: "#2E3036",
    inversePrimary: "#405F90",
    primaryFixed: "#D6E3FF",
    onPrimaryFixed: "#001B3D",
    primaryFixedDim: "#A9C7FF",
    onPrimaryFixedVariant: "#264777",
    secondaryFixed: "#D9E3F9",
    onSecondaryFixed: "#121C2B",
    secondaryFixedDim: "#BDC7DC",
    onSecondaryFixedVariant: "#3E4758",
    tertiaryFixed: "#F9D8FD",
    onTertiaryFixed: "#28132F",
    tertiaryFixedDim: "#DCBCE1",
    onTertiaryFixedVariant: "#563E5C",
    surfaceDim: "#111318",
    surfaceBright: "#37393E",
    surfaceContainerLowest: "#0C0E13",
    surfaceContainerLow: "#191C20",
    surfaceContainer: "#1D2024",
    surfaceContainerHigh: "#282A2F",
    surfaceContainerHighest: "#33353A",
  },
};

export const Colors = {
  light: nutrisyncColors.light,
  dark: nutrisyncColors.dark,
};

export const GlobalColors = {
  checkGreen: "#4CAF50",
  green: "#34b233",
  yellow: "",
  light: {
    bottomBarActiveTint: "#000",
    bottomBarInactiveTint: "#666",
    bottomBarBarBackground: "#fff",
    bottomBarBorderTop: "#ccc",
  },
  dark: {
    bottomBarActiveTint: "#fff",
    bottomBarInactiveTint: "#888",
    bottomBarBarBackground: "#121212",
    bottomBarBorderTop: "#333",
  },
};
