import { useFoodRepository as useRepositoryContext } from "@/context/RepositoriesProvider";
import { FoodData } from "@/models/interfaces/FoodData";
import { SearchOptions, SearchResult } from "@/utils/repositories/FoodDataRepository";
import { useCallback } from "react";

/**
 * Hook for accessing and manipulating food data
 * Provides methods for CRUD operations on food items
 */
export const useFoodRepository = () => {
  const foodRepository = useRepositoryContext();

  /**
   * Get a food item by ID
   */
  const getFood = useCallback(
    async (id: string) => {
      return await foodRepository.get(id);
    },
    [foodRepository]
  );

  /**
   * Search for food items with pagination
   */
  const searchFoods = useCallback(
    async (options: SearchOptions) => {
      return await foodRepository.search(options);
    },
    [foodRepository]
  );

  /**
   * Get all food items from local storage (offline use only)
   */
  const getAllLocalFoods = useCallback(async () => {
    return await foodRepository.getAllLocal();
  }, [foodRepository]);

  /**
   * Save a new food item
   * ID will be generated by the server or database
   */
  const saveFood = useCallback(
    async (food: Omit<FoodData, "id" | "created_at" | "updated_at">) => {
      const now = new Date().toISOString();
      const foodWithTimestamps: FoodData = {
        ...food,
        id: `temp_${Date.now()}`, // Temporary ID that will be replaced by the server
        created_at: now,
        updated_at: now,
      };

      return await foodRepository.save(foodWithTimestamps);
    },
    [foodRepository]
  );

  /**
   * Update specific fields of a food item
   */
  const updateFood = useCallback(
    async (id: string, patch: Partial<FoodData>) => {
      await foodRepository.update(id, {
        ...patch,
        updated_at: new Date().toISOString(),
      });
    },
    [foodRepository]
  );

  /**
   * Delete a food item
   */
  const deleteFood = useCallback(
    async (id: string) => {
      await foodRepository.delete(id);
    },
    [foodRepository]
  );

  return {
    getFood,
    searchFoods,
    getAllLocalFoods,
    saveFood,
    updateFood,
    deleteFood,
  };
};
